// ═══════════════════════════════════════════════════════════════
// bbr-extra-großschreibung.js  –  Groß- und Kleinschreibung (9. Klasse)
// ═══════════════════════════════════════════════════════════════
var BBR_EXTRA_THEMES = [
  {
    id: "bbr_extra_grossklein",
    title: "Groß- und Kleinschreibung",
    emoji: "🔠",
    color: "#dc2626",
    qs: [
      { sub:"Nominalisiertes Verb", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Das ___ der Kerzen war stimmungsvoll.“ – groß oder klein? (leuchten)",
        rows:["leuchten / Leuchten"], cols:["groß (Nomen)","klein (Verb)"], correct:[0],
        model:"das Leuchten → Artikel ‚das' zeigt Nomen → groß.",
        rule:"<div class=rbox>Verben werden großgeschrieben, wenn sie als Nomen gebraucht werden – erkennbar an Begleitern wie <span class=hl>das, ein, beim, zum</span>.</div>" },
      { sub:"Nominalisiertes Verb", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Beim ___ muss man auf den Takt achten.“ (tanzen)",
        rows:["tanzen / Tanzen"], cols:["groß (Nomen)","klein (Verb)"], correct:[0],
        model:"beim Tanzen → nach ‚beim' steht Nomen → groß.",
        rule:"<div class=rbox>Nach Präpositionen wie <span class=hl>beim, zum, im, am</span> steht das nominalisierte Verb → Großschreibung.</div>" },
      { sub:"Nominalisiertes Verb", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Die Kinder ___ draußen.“ (spielen)",
        rows:["spielen / Spielen"], cols:["groß (Nomen)","klein (Verb)"], correct:[1],
        model:"Die Kinder spielen → normales Verb → klein.",
        rule:"<div class=rbox>Steht kein Artikel oder Pronomen davor, bleibt das Verb klein.</div>" },
      { sub:"Nominalisiertes Verb", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Sein ständiges ___ nervte alle.“ (klagen)",
        rows:["klagen / Klagen"], cols:["groß (Nomen)","klein (Verb)"], correct:[0],
        model:"sein … Klagen → Possessivpronomen vor Nomen → groß.",
        rule:"<div class=rbox>Nach Possessivpronomen (mein, dein, sein …) wird das nominalisierte Verb großgeschrieben.</div>" },
      { sub:"Nominalisiertes Verb", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Zum ___ brauchst du viel Ausdauer.“ (schweißen)",
        rows:["schweißen / Schweißen"], cols:["groß (Nomen)","klein (Verb)"], correct:[0],
        model:"zum Schweißen → nach ‚zum' Nomen → groß.",
        rule:"<div class=rbox>Nach <span class=hl>zum, beim, im, am</span> steht das nominalisierte Verb → Großschreibung.</div>" },
      { sub:"Nominalisiertes Verb", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Das ___ der Birken im Wind beruhigte sie.“ (rauschen)",
        rows:["rauschen / Rauschen"], cols:["groß (Nomen)","klein (Verb)"], correct:[0],
        model:"das Rauschen → Artikel ‚das' → Nomen → groß.",
        rule:"<div class=rbox>Artikel + Verb = Nominalisierung → Großschreibung.</div>" },
      { sub:"Nominalisiertes Verb", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Sie ___ lautstark.“ (lachen)",
        rows:["lachen / Lachen"], cols:["groß (Nomen)","klein (Verb)"], correct:[1],
        model:"Sie lachen → normales Verb → klein.",
        rule:"<div class=rbox>Kein Signalwort vor dem Verb → bleibt klein.</div>" },
      { sub:"Nominalisiertes Verb", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Ihr ___ hat uns alle angesteckt.“ (lachen)",
        rows:["lachen / Lachen"], cols:["groß (Nomen)","klein (Verb)"], correct:[0],
        model:"Ihr Lachen → Possessivpronomen ‚Ihr' → Nomen → groß.",
        rule:"<div class=rbox>Nach <span class=hl>Possessivpronomen</span> steht das nominalisierte Verb groß.</div>" },
      { sub:"Substantiviertes Adjektiv", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Das war etwas ganz ___.“ (besonders)",
        rows:["Besonderes / besonderes"], cols:["groß","klein"], correct:[0],
        model:"etwas Besonderes → nach ‚etwas' wird das Adjektiv zum Nomen → groß.",
        rule:"<div class=rbox>Adjektive nach <span class=hl>etwas, nichts, alles, viel, wenig</span> werden als Nomen großgeschrieben.</div>" },
      { sub:"Substantiviertes Adjektiv", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Sie hatte nichts ___ zu erzählen.“ (neu)",
        rows:["Neues / neues"], cols:["groß","klein"], correct:[0],
        model:"nichts Neues → nach ‚nichts' substantiviertes Adjektiv → groß.",
        rule:"<div class=rbox>Nach <span class=hl>nichts</span> wird das folgende Adjektiv großgeschrieben.</div>" },
      { sub:"Substantiviertes Adjektiv", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Das ___ an ihrem Stil ist die Klarheit.“ (besondere)",
        rows:["Besondere / besondere"], cols:["groß","klein"], correct:[0],
        model:"Das Besondere → mit Artikel substantiviert → groß.",
        rule:"<div class=rbox>Adjektiv mit Artikel (das …) → Nomen → Großschreibung.</div>" },
      { sub:"Adjektiv vor Nomen", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Sie trug ein ___ Kleid.“ (rotes)",
        rows:["Rotes / rotes"], cols:["groß","klein"], correct:[1],
        model:"ein rotes Kleid → Adjektiv beschreibt ein Nomen → klein.",
        rule:"<div class=rbox>Adjektive, die direkt vor einem Nomen stehen, bleiben kleingeschrieben.</div>" },
      { sub:"Höflichkeitspronomen", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Haben ___ den Brief erhalten?“ (formelle Anrede)",
        rows:["Sie / sie"], cols:["groß (Höflichkeit)","klein (3. Person)"], correct:[0],
        model:"Höflichkeitsanrede → Sie großschreiben.",
        rule:"<div class=rbox>Das Höflichkeitspronomen <span class=hl>Sie, Ihnen, Ihr</span> wird immer großgeschrieben.</div>" },
      { sub:"Höflichkeitspronomen", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Darf ich ___ etwas fragen?“ (formell, Dativ)",
        rows:["Ihnen / ihnen"], cols:["groß (Höflichkeit)","klein (informell)"], correct:[0],
        model:"Formelle Anrede → Ihnen großschreiben.",
        rule:"<div class=rbox><span class=hl>Ihnen</span> ist der Dativ von Sie (Höflichkeit) → groß.</div>" },
      { sub:"Höflichkeitspronomen", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Habt ___ das schon gehört?“ (informell, Gruppe)",
        rows:["Ihr / ihr"], cols:["groß (Höflichkeit)","klein (informell)"], correct:[1],
        model:"Informelle Gruppenanrede → ihr klein.",
        rule:"<div class=rbox>Das informelle Pronomen <span class=hl>ihr</span> wird kleingeschrieben.</div>" },
      { sub:"Feste Wendung", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Sie hat ___ Angst vor dem Gewitter.“ (Angst / angst)",
        rows:["Angst / angst"], cols:["groß (Nomen)","klein (Adverb)"], correct:[0],
        model:"Angst haben → Angst ist Nomen → groß.",
        rule:"<div class=rbox>In der Wendung <span class=hl>Angst haben</span> ist Angst ein Nomen → Großschreibung.</div>" },
      { sub:"Feste Wendung", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Da hast du ___.“ (= du hast die richtige Meinung, recht/Recht)",
        rows:["Recht / recht"], cols:["groß (Nomen)","klein (Adverb)"], correct:[1],
        model:"recht haben → recht ist Adverb (= richtig) → klein.",
        rule:"<div class=rbox>In der Wendung <span class=hl>recht haben</span> ist recht ein Adverb → Kleinschreibung.</div>" },
      { sub:"Feste Wendung", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Sie bekam vor Gericht ___.“ (= ihr wurde Recht zugesprochen)",
        rows:["Recht / recht"], cols:["groß (Nomen)","klein (Adverb)"], correct:[0],
        model:"Recht bekommen → Recht als Nomen → groß.",
        rule:"<div class=rbox><span class=hl>Recht bekommen/geben</span>: Recht ist Nomen → groß.</div>" },
      { sub:"Sprache als Nomen", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Sie spricht fließend ___.“ (Landessprache Deutschlands)",
        rows:["Deutsch / deutsch"], cols:["groß (Sprache als Nomen)","klein (Adjektiv)"], correct:[0],
        model:"Sprachen als Nomen → Deutsch groß.",
        rule:"<div class=rbox>Sprachbezeichnungen als Nomen (‚sie spricht Deutsch') werden großgeschrieben.</div>" },
      { sub:"Adjektiv der Nationalität", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Ein ___ Abend im Restaurant.“ (aus Deutschland stammend)",
        rows:["Deutsches / deutsches"], cols:["groß","klein"], correct:[1],
        model:"ein deutsches Restaurant → Adjektiv vor Nomen → klein.",
        rule:"<div class=rbox>Adjektive vor Nomen bleiben klein: <span class=hl>deutsches Brot, türkische Musik</span>.</div>" },
      { sub:"Farbbezeichnung", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Bei ___ musst du anhalten.“ (Ampelfarbe)",
        rows:["Rot / rot"], cols:["groß (Nomen)","klein (Adjektiv)"], correct:[0],
        model:"bei Rot → Farbe als Nomen (nach Präposition) → groß.",
        rule:"<div class=rbox>Farbbezeichnungen nach Präpositionen (bei Rot, in Grün) → als Nomen → groß.</div>" },
      { sub:"Farbbezeichnung", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Er trägt ein ___ Hemd.“ (Farbe)",
        rows:["Blaues / blaues"], cols:["groß (Nomen)","klein (Adjektiv)"], correct:[1],
        model:"ein blaues Hemd → Adjektiv vor Nomen → klein.",
        rule:"<div class=rbox>Farbwörter als Adjektive vor Nomen bleiben klein.</div>" },
      { sub:"Fehler finden", type:"mc",
        q:"<b>Erkenne</b> den Fehler:\nWelcher Satz enthält einen Fehler?",
        o:["Das Schwimmen macht mir Spaß.","Beim Laufen schwitze ich.","Er geht zum einkaufen.","Das Tanzen ist sein Hobby."],
        c:2, model:"zum einkaufen → nach ‚zum' muss groß stehen: zum Einkaufen.",
        rule:"<div class=rbox>Nach <span class=hl>zum, beim, im, am</span> steht das nominalisierte Verb → Großschreibung.</div>" },
      { sub:"Korrekten Satz finden", type:"mc",
        q:"<b>Wähle</b> den richtigen Satz aus:\nWelcher Satz ist korrekt geschrieben?",
        o:["Das lesen macht Spaß.","Das Lesen macht Spaß.","das Lesen macht spaß.","Das lesen macht spaß."],
        c:1, model:"Das Lesen → Nomen (mit Artikel) → groß. Übrige Wörter korrekt.",
        rule:"<div class=rbox>Nominalisiertes Verb nach Artikel: <span class=hl>das Lesen</span> → groß.</div>" },
      { sub:"Korrekte Schreibung", type:"mc",
        q:"<b>Bilde</b>:\nWie lautet die korrekte Schreibung?\n\n„im großen und ganzen bin ich zufrieden.“",
        o:["im Großen und ganzen","Im großen und Ganzen","im Großen und Ganzen","Im Großen und Ganzen"],
        c:2, model:"Im Großen und Ganzen → feste Wendung mit nominalisierten Adjektiven, beide groß; ‚im' klein (Satzmitte).",
        rule:"<div class=rbox>Feste Wendung: <span class=hl>im Großen und Ganzen</span> – nominalisierte Adjektive groß.</div>" },
      { sub:"Zuordnung", type:"match",
        q:"<b>Ordne</b> jede Wendung der richtigen Schreibweise zu.",
        pairs:[
          ["beim ___ (radeln)","Radeln"],
          ["etwas ___ (wichtig)","Wichtiges"],
          ["ein ___ Tag (schön)","schöner"],
          ["zum ___ (kochen)","Kochen"]
        ],
        model:"Radeln/Kochen nach beim/zum → groß; Wichtiges nach etwas → groß; schöner vor Nomen → klein.",
        rule:"<div class=rbox>Nominalisierte Verben und substantivierte Adjektive groß, Adjektive vor Nomen klein.</div>" }
    ]
  }
,
  {
    id: "bbr_extra_nominalisierung",
    title: "Nominalisierung von Verben",
    emoji: "📝",
    color: "#16a34a",
    qs: [
      { sub:"Signalwort erkennen", type:"mc",
        q:"<b>Benenne</b>:\nWas zeigt an, dass ein Verb nominalisiert (großgeschrieben) werden muss?",
        o:["Ein Nomen steht dahinter.","Ein Artikel, Pronomen oder Präposition steht davor.","Das Verb steht am Satzende.","Ein Komma steht davor."],
        c:1, model:"Signalwörter: Artikel (das), Präpositionen (beim, zum) oder Pronomen (mein, sein).",
        rule:"<div class=rbox>Nominalisierte Verben erkennst du an vorausgehenden <span class=hl>Artikeln, Pronomen oder Präpositionen</span>.</div>" },
      { sub:"Nominalisierung", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Das ___ eines Pflaumenbaums ist anstrengend.“ (pflanzen)",
        rows:["pflanzen / Pflanzen"], cols:["groß (Nomen)","klein (Verb)"], correct:[0],
        model:"das Pflanzen → Artikel ‚das' → Nomen → groß.",
        rule:"<div class=rbox>Artikel + Verb = Nominalisierung → Großschreibung.</div>" },
      { sub:"Nominalisierung", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Wir wollen morgen früh ___.“ (aufwachen)",
        rows:["aufwachen / Aufwachen"], cols:["groß (Nomen)","klein (Verb)"], correct:[1],
        model:"normales Verb ohne Signalwort → klein.",
        rule:"<div class=rbox>Kein Signalwort vor dem Verb → bleibt klein.</div>" },
      { sub:"Nominalisierung", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Ihr ___ hat uns alle angesteckt.“ (lachen)",
        rows:["lachen / Lachen"], cols:["groß (Nomen)","klein (Verb)"], correct:[0],
        model:"Ihr Lachen → Possessivpronomen → Nomen → groß.",
        rule:"<div class=rbox>Nach <span class=hl>Possessivpronomen</span> (mein, dein, ihr …) steht das nominalisierte Verb groß.</div>" },
      { sub:"Nominalisierung Adjektiv", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Das ___ dieser Komposition begeisterte alle.“ (genial)",
        rows:["Geniale / geniale"], cols:["groß","klein"], correct:[0],
        model:"Das Geniale → Adjektiv mit Artikel → Nomen → groß.",
        rule:"<div class=rbox>Adjektive mit Artikel werden zu Nomen: <span class=hl>das Geniale, das Schöne</span> → groß.</div>" },
      { sub:"Nominalisierung Adjektiv", type:"cross", isSingle:true,
        q:"<b>Entscheide</b>:\n„Das war ein ___ Auftritt.“ (genial)",
        rows:["Genialer / genialer"], cols:["groß","klein"], correct:[1],
        model:"ein genialer Auftritt → Adjektiv vor Nomen → klein.",
        rule:"<div class=rbox>Adjektiv vor Nomen → bleibt klein.</div>" },
      { sub:"Erklärung", type:"mc",
        q:"<b>Erkläre</b>:\nWarum schreibt man ‚das Schwimmen' groß?",
        o:["Weil es am Satzanfang steht.","Weil es ein Verb ist.","Weil es mit dem Artikel ‚das' ein Nomen bildet.","Weil es ein Adjektiv ist."],
        c:2, model:"Das Schwimmen → Verb wird durch Artikel ‚das' zum Nomen → Großschreibung.",
        rule:"<div class=rbox>Nominalisiertes Verb mit Artikel → Großschreibung.</div>" },
      { sub:"Signalwörter", type:"match",
        q:"<b>Ordne</b> das Verb der richtigen nominalisierten Form zu.",
        pairs:[
          ["spielen → das ___","Spielen"],
          ["tanzen → beim ___","Tanzen"],
          ["laufen → zum ___","Laufen"],
          ["schreiben → mein ___","Schreiben"]
        ],
        model:"Alle Verben nach Signalwörtern (das, beim, zum, mein) großschreiben.",
        rule:"<div class=rbox>Signalwörter → Verb wird zum Nomen → Großschreibung.</div>" },
      { sub:"Fehler finden", type:"mc",
        q:"<b>Erkenne</b> den Fehler:\nWelcher Satz enthält einen Fehler?",
        o:["Das Lesen macht Spaß.","Beim Kochen braucht man Geduld.","zum schreiben brauche ich einen Stift.","Mein Tanzen hat sich verbessert."],
        c:2, model:"zum schreiben → nach ‚zum' muss großgeschrieben werden: zum Schreiben.",
        rule:"<div class=rbox>Nach <span class=hl>zum</span> steht das nominalisierte Verb → Großschreibung.</div>" },
      { sub:"Nominalisierung erkennen", type:"mc",
        q:"<b>Erkenne</b>:\nIn welchem Satz liegt eine Nominalisierung vor?",
        o:["Sie singt schön.","Das Singen macht ihr Freude.","Er singt jeden Tag.","Ich höre sie singen."],
        c:1, model:"Das Singen → Artikel ‚das' → Nominalisierung.",
        rule:"<div class=rbox>Nominalisierung: Verb mit Artikel → <span class=hl>das Singen</span>.</div>" },
      { sub:"Anwendung", type:"mc",
        q:"<b>Wende</b> die Regel an:\nWelche Schreibweise ist korrekt?\n„Sie liebt das ___ im Regen.“",
        o:["spazierengehen","Spazierengehen","spazieren Gehen","Spazieren-gehen"],
        c:1, model:"das Spazierengehen → Nomen → groß, zusammengeschrieben.",
        rule:"<div class=rbox>Nominalisierung: <span class=hl>das Spazierengehen</span> → zusammen und groß.</div>" },
      { sub:"Überblick", type:"mc",
        q:"<b>Wähle</b> die richtige Antwort aus:\nWelche der folgenden Möglichkeiten ist KEIN Signalwort für Nominalisierung?",
        o:["das (Artikel)","beim (Präposition)","obwohl (Konjunktion)","mein (Pronomen)"],
        c:2, model:"obwohl ist eine Konjunktion und kein Signalwort für Nominalisierung.",
        rule:"<div class=rbox>Signalwörter: Artikel (das), Präpositionen (beim, zum), Pronomen (mein). Konjunktionen (weil, obwohl) sind kein Signal.</div>" },
      { sub:"Vertiefung", type:"mc",
        q:"<b>Bilde</b>:\nWie lautet die Nominalisierung von ‚schwimmen' im Satz:„Er geht täglich ___.“",
        o:["Schwimmen (groß)","schwimmen (klein)","geschwommen","Schwimmend"],
        c:1, model:"Er geht schwimmen → kein Signalwort davor → normales Verb → klein.",
        rule:"<div class=rbox>Ohne Signalwort bleibt das Verb klein: Er geht schwimmen.</div>" },
      { sub:"Komplexe Aufgabe", type:"mc",
        q:"<b>Wähle</b> die richtige Antwort aus:\n„Ich freue mich auf das ___ mit dir.“– groß oder klein? (spazieren gehen)",
        o:["das spazieren gehen","das Spazierengehen","das Spazieren Gehen","das spazierenGehen"],
        c:1, model:"das Spazierengehen → Artikel ‚das' → Nomen → groß und zusammengeschrieben.",
        rule:"<div class=rbox>Nominalisiertes Verb mit Artikel: <span class=hl>das Spazierengehen</span>.</div>" }
    ]
  }
];